global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'meowai-home'
    static_configs:
      - targets: ['meowai:8000']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 10s
